// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

using System;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace GoCardless.Tests
{
    // Simple mock HTTP handler for code samples that accepts raw JSON strings
    public class MockHttpForCodeSamples : HttpMessageHandler
    {
        private readonly System.Collections.Generic.Queue<HttpResponseMessage> _queuedMessages =
            new System.Collections.Generic.Queue<HttpResponseMessage>();

        public void EnqueueStringResponse(int statusCode, string body)
        {
            var httpResponseMessage = new HttpResponseMessage((HttpStatusCode)statusCode)
            {
                Content = new StringContent(body, Encoding.UTF8, "application/json"),
            };
            _queuedMessages.Enqueue(httpResponseMessage);
        }

        protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            System.Threading.CancellationToken cancellationToken
        )
        {
            return Task.FromResult(_queuedMessages.Dequeue());
        }
    }
}
