// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Test
// This test verifies that a documentation code sample is syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: This test does NOT verify business logic - it only verifies that
// the code sample compiles and executes without syntax errors.

using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using GoCardless.Resources;
using GoCardless.Services;
using NUnit.Framework;

namespace GoCardless.Tests
{
    public class CustomersCreateCodeSampleTest
    {
        private GoCardlessClient client;
        private MockHttpForCodeSamples http;

        [SetUp]
        public void SetUp()
        {
            http = new MockHttpForCodeSamples();
            var httpClient = new HttpClient(http);
            client = GoCardlessClient.Create("SECRET_TOKEN", "https://api.example.com", httpClient);
        }

        [Test]
        public async Task CreateCodeSampleExecutesWithoutError()
        {
            // Mock response - enqueue multiple times to handle code samples with multiple API calls
            string responseBody = "{ \"customers\": {} }";
            for (int i = 0; i < 5; i++)
            {
                http.EnqueueStringResponse(200, responseBody);
            }

            // Suppress console output from code samples
            var originalOut = Console.Out;
            Console.SetOut(TextWriter.Null);

            try
            {
                var customerRequest = new GoCardless.Services.CustomerCreateRequest()
                {
                    Email = "user@example.com",
                    GivenName = "Frank",
                    FamilyName = "Osborne",
                    AddressLine1 = "27 Acer Road",
                    AddressLine2 = "Apt 2",
                    City = "London",
                    PostalCode = "E8 3GX",
                    CountryCode = "GB",
                    Metadata = new Dictionary<string, string>() { { "salesforce_id", "ABCD1234" } },
                };

                var customerResponse = await client.Customers.CreateAsync(customerRequest);
                GoCardless.Resources.Customer customer = customerResponse.Customer;
            }
            finally
            {
                Console.SetOut(originalOut);
            }
        }
    }
}
