// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Test
// This test verifies that a documentation code sample is syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: This test does NOT verify business logic - it only verifies that
// the code sample compiles and executes without syntax errors.

using System;
using System.Collections.Generic;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using GoCardless.Resources;
using GoCardless.Services;
using GoCardless.Services;
using NUnit.Framework;

namespace GoCardless.Tests
{
    public class InstalmentSchedulesCreateWithScheduleCodeSampleTest
    {
        private GoCardlessClient client;
        private MockHttpForCodeSamples http;

        [SetUp]
        public void SetUp()
        {
            http = new MockHttpForCodeSamples();
            var httpClient = new HttpClient(http);
            client = GoCardlessClient.Create("SECRET_TOKEN", "https://api.example.com", httpClient);
        }

        [Test]
        public async Task CreateWithScheduleCodeSampleExecutesWithoutError()
        {
            // Mock response - enqueue multiple times to handle code samples with multiple API calls
            string responseBody = "{ \"instalment_schedules\": {} }";
            for (int i = 0; i < 5; i++)
            {
                http.EnqueueStringResponse(200, responseBody);
            }

            // Suppress console output from code samples
            var originalOut = Console.Out;
            Console.SetOut(TextWriter.Null);

            try
            {
                int?[] amountsArray = new int?[] { 3400, 3400, 3200 };
                var createResponse = await client.InstalmentSchedules.CreateWithScheduleAsync(
                    new InstalmentScheduleCreateWithScheduleRequest
                    {
                        TotalAmount = 10000, // 100 GBP in pence, collected from the customer
                        AppFee = 10, // Your 10 pence fee, applied to each instalment,
                        // to be paid out to you
                        Currency = InstalmentScheduleCreateWithScheduleRequest
                            .InstalmentScheduleCurrency
                            .GBP,
                        Name = "ACME Invoice 103",
                        Instalments =
                            new InstalmentScheduleCreateWithScheduleRequest.InstalmentScheduleInstalments
                            {
                                StartDate = "2019-08-20",
                                IntervalUnit = InstalmentScheduleCreateWithScheduleRequest
                                    .InstalmentScheduleInstalments
                                    .InstalmentScheduleIntervalUnit
                                    .Weekly,
                                Interval = 2,
                                Amounts = amountsArray,
                            },
                        Metadata = new Dictionary<string, string> { { "Invoice ID", "001" } },
                        Links =
                            new InstalmentScheduleCreateWithScheduleRequest.InstalmentScheduleLinks
                            {
                                Mandate = "MD0000XH9A3T4C",
                            },
                        IdempotencyKey = "random_instalment_schedule_specific_string",
                    }
                );
            }
            finally
            {
                Console.SetOut(originalOut);
            }
        }
    }
}
