// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Test
// This test verifies that a documentation code sample is syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: This test does NOT verify business logic - it only verifies that
// the code sample compiles and executes without syntax errors.

using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using GoCardless.Resources;
using GoCardless.Services;
using NUnit.Framework;

namespace GoCardless.Tests
{
    public class MandatePdfsCreateCodeSampleTest
    {
        private GoCardlessClient client;
        private MockHttpForCodeSamples http;

        [SetUp]
        public void SetUp()
        {
            http = new MockHttpForCodeSamples();
            var httpClient = new HttpClient(http);
            client = GoCardlessClient.Create("SECRET_TOKEN", "https://api.example.com", httpClient);
        }

        [Test]
        public async Task CreateCodeSampleExecutesWithoutError()
        {
            // Mock response - enqueue multiple times to handle code samples with multiple API calls
            string responseBody = "{ \"mandate_pdfs\": {} }";
            for (int i = 0; i < 5; i++)
            {
                http.EnqueueStringResponse(200, responseBody);
            }

            // Suppress console output from code samples
            var originalOut = Console.Out;
            Console.SetOut(TextWriter.Null);

            try
            {
                var mandatePdfForMandateRequest = new GoCardless.Services.MandatePdfCreateRequest()
                {
                    Links = new GoCardless.Services.MandatePdfCreateRequest.MandatePdfLinks()
                    {
                        Mandate = "MD123",
                    },
                };

                var mandatePdfForMandateResponse = await client.MandatePdfs.CreateAsync(
                    mandatePdfForMandateRequest
                );
                GoCardless.Resources.MandatePdf mandatePdfForMandate =
                    mandatePdfForMandateResponse.MandatePdf;

                var mandatePdfForBankDetailsRequest =
                    new GoCardless.Services.MandatePdfCreateRequest()
                    {
                        AccountNumber = "55779911",
                        BranchCode = "200000",
                        CountryCode = "GB",
                    };

                var mandatePdfForBankDetailsResponse = await client.MandatePdfs.CreateAsync(
                    mandatePdfForBankDetailsRequest
                );
                GoCardless.Resources.MandatePdf mandatePdfForBankDetails =
                    mandatePdfForBankDetailsResponse.MandatePdf;

                var mandatePdfWithIbanRequest = new GoCardless.Services.MandatePdfCreateRequest()
                {
                    Iban = "FR14BARC20000055779911",
                };

                var mandatePdfWithIbanResponse = await client.MandatePdfs.CreateAsync(
                    mandatePdfWithIbanRequest
                );
                GoCardless.Resources.MandatePdf mandatePdfWithIban =
                    mandatePdfWithIbanResponse.MandatePdf;

                var requestSettings = new GoCardless.Internals.RequestSettings
                {
                    CustomiseRequestMessage = (request) =>
                    {
                        request.Headers.Add("Accept-Language", "fr");
                    },
                };

                var frenchMandatePdfRequest = new GoCardless.Services.MandatePdfCreateRequest();
                var frenchMandatePdfResponse = await client.MandatePdfs.CreateAsync(
                    frenchMandatePdfRequest,
                    requestSettings
                );
                GoCardless.Resources.MandatePdf frenchMandatePdf =
                    frenchMandatePdfResponse.MandatePdf;
            }
            finally
            {
                Console.SetOut(originalOut);
            }
        }
    }
}
