// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Test
// This test verifies that a documentation code sample is syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: This test does NOT verify business logic - it only verifies that
// the code sample compiles and executes without syntax errors.

using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using GoCardless.Resources;
using GoCardless.Services;
using NUnit.Framework;

namespace GoCardless.Tests
{
    public class MandateImportEntriesCreateCodeSampleTest
    {
        private GoCardlessClient client;
        private MockHttpForCodeSamples http;

        [SetUp]
        public void SetUp()
        {
            http = new MockHttpForCodeSamples();
            var httpClient = new HttpClient(http);
            client = GoCardlessClient.Create("SECRET_TOKEN", "https://api.example.com", httpClient);
        }

        [Test]
        public async Task CreateCodeSampleExecutesWithoutError()
        {
            // Mock response - enqueue multiple times to handle code samples with multiple API calls
            string responseBody = "{ \"mandate_import_entries\": {} }";
            for (int i = 0; i < 5; i++)
            {
                http.EnqueueStringResponse(200, responseBody);
            }

            // Suppress console output from code samples
            var originalOut = Console.Out;
            Console.SetOut(TextWriter.Null);

            try
            {
                var request = new GoCardless.Services.MandateImportEntryCreateRequest()
                {
                    Customer =
                        new GoCardless.Services.MandateImportEntryCreateRequest.MandateImportEntryCustomer()
                        {
                            CompanyName = "Jane's widgets",
                            Email = "jane@janeswidgets.fr",
                        },
                    BankAccount =
                        new GoCardless.Services.MandateImportEntryCreateRequest.MandateImportEntryBankAccount()
                        {
                            AccountHolderName = "Jane Doe",
                            Iban = "FR14BARC20000055779911",
                        },
                    Amendment =
                        new GoCardless.Services.MandateImportEntryCreateRequest.MandateImportEntryAmendment()
                        {
                            OriginalMandateReference = "REFNMANDATE",
                            OriginalCreditorId = "FR123OTHERBANK",
                            OriginalCreditorName = "Existing DD Provider",
                        },
                    Links =
                        new GoCardless.Services.MandateImportEntryCreateRequest.MandateImportEntryLinks()
                        {
                            MandateImport = "IM000010790WX1",
                        },
                };

                var importResponse = await client.MandateImportEntries.CreateAsync(request);
                GoCardless.Resources.MandateImportEntry entry = importResponse.MandateImportEntry;
            }
            finally
            {
                Console.SetOut(originalOut);
            }
        }
    }
}
