// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Test
// This test verifies that a documentation code sample is syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: This test does NOT verify business logic - it only verifies that
// the code sample compiles and executes without syntax errors.

using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using GoCardless.Resources;
using GoCardless.Services;
using NUnit.Framework;

namespace GoCardless.Tests
{
    public class PayerAuthorisationsUpdateCodeSampleTest
    {
        private GoCardlessClient client;
        private MockHttpForCodeSamples http;

        [SetUp]
        public void SetUp()
        {
            http = new MockHttpForCodeSamples();
            var httpClient = new HttpClient(http);
            client = GoCardlessClient.Create("SECRET_TOKEN", "https://api.example.com", httpClient);
        }

        [Test]
        public async Task UpdateCodeSampleExecutesWithoutError()
        {
            // Mock response - enqueue multiple times to handle code samples with multiple API calls
            string responseBody = "{ \"payer_authorisations\": {} }";
            for (int i = 0; i < 5; i++)
            {
                http.EnqueueStringResponse(200, responseBody);
            }

            // Suppress console output from code samples
            var originalOut = Console.Out;
            Console.SetOut(TextWriter.Null);

            try
            {
                var customer =
                    new GoCardless.Services.PayerAuthorisationUpdateRequest.PayerAuthorisationCustomer()
                    {
                        Email = "mail@example.com",
                        GivenName = "Name",
                        FamilyName = "Surname",
                        Metadata = new Dictionary<string, string>
                        {
                            { "salesforce_id", "EFGH5678" },
                        },
                    };
                var bankAccount =
                    new GoCardless.Services.PayerAuthorisationUpdateRequest.PayerAuthorisationBankAccount()
                    {
                        AccountHolderName = "Name Surname",
                        BranchCode = "200000",
                        AccountNumber = "55779911",
                    };
                var mandate =
                    new GoCardless.Services.PayerAuthorisationUpdateRequest.PayerAuthorisationMandate()
                    {
                        Reference = "XYZ789",
                    };
                var PayerAuthorisationRequest =
                    new GoCardless.Services.PayerAuthorisationUpdateRequest()
                    {
                        Customer = customer,
                        BankAccount = bankAccount,
                        Mandate = mandate,
                    };
                var PayerAuthorisationResponse = await client.PayerAuthorisations.UpdateAsync(
                    "PA123",
                    PayerAuthorisationRequest
                );
            }
            finally
            {
                Console.SetOut(originalOut);
            }
        }
    }
}
