// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Test
// This test verifies that a documentation code sample is syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: This test does NOT verify business logic - it only verifies that
// the code sample compiles and executes without syntax errors.

using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using GoCardless.Resources;
using GoCardless.Services;
using NUnit.Framework;

namespace GoCardless.Tests
{
    public class RedirectFlowsCreateCodeSampleTest
    {
        private GoCardlessClient client;
        private MockHttpForCodeSamples http;

        [SetUp]
        public void SetUp()
        {
            http = new MockHttpForCodeSamples();
            var httpClient = new HttpClient(http);
            client = GoCardlessClient.Create("SECRET_TOKEN", "https://api.example.com", httpClient);
        }

        [Test]
        public async Task CreateCodeSampleExecutesWithoutError()
        {
            // Mock response - enqueue multiple times to handle code samples with multiple API calls
            string responseBody = "{ \"redirect_flows\": {} }";
            for (int i = 0; i < 5; i++)
            {
                http.EnqueueStringResponse(200, responseBody);
            }

            // Suppress console output from code samples
            var originalOut = Console.Out;
            Console.SetOut(TextWriter.Null);

            try
            {
                var prefilledCustomer =
                    new GoCardless.Services.RedirectFlowCreateRequest.RedirectFlowPrefilledCustomer()
                    {
                        AddressLine1 = "338 Goswell Road",
                        Email = "api@gocardless.com",
                        GivenName = "Bobby",
                        FamilyName = "Tables",
                    };

                var redirectFlowRequest = new GoCardless.Services.RedirectFlowCreateRequest()
                {
                    Description = "Gold package",
                    SessionToken = "SESS_wSs0uGYMISxzqOBq",
                    SuccessRedirectUrl = "https://example.com/pay/confirm",
                    PrefilledCustomer = prefilledCustomer,
                };

                var redirectFlowResponse = await client.RedirectFlows.CreateAsync(
                    redirectFlowRequest
                );
                GoCardless.Resources.RedirectFlow redirectFlow = redirectFlowResponse.RedirectFlow;

                Console.WriteLine(redirectFlow.RedirectUrl);
            }
            finally
            {
                Console.SetOut(originalOut);
            }
        }
    }
}
