// WARNING: Do not edit by hand, this file was generated by Crank:
//
//   https://github.com/gocardless/crank
//

// Code Sample Test
// This test verifies that a documentation code sample is syntactically valid
// and can execute against a mocked API without errors.
//
// IMPORTANT: This test does NOT verify business logic - it only verifies that
// the code sample compiles and executes without syntax errors.

using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using GoCardless.Resources;
using GoCardless.Services;
using NUnit.Framework;

namespace GoCardless.Tests
{
    public class VerificationDetailsCreateCodeSampleTest
    {
        private GoCardlessClient client;
        private MockHttpForCodeSamples http;

        [SetUp]
        public void SetUp()
        {
            http = new MockHttpForCodeSamples();
            var httpClient = new HttpClient(http);
            client = GoCardlessClient.Create("SECRET_TOKEN", "https://api.example.com", httpClient);
        }

        [Test]
        public async Task CreateCodeSampleExecutesWithoutError()
        {
            // Mock response - enqueue multiple times to handle code samples with multiple API calls
            string responseBody = "{ \"verification_details\": {} }";
            for (int i = 0; i < 5; i++)
            {
                http.EnqueueStringResponse(200, responseBody);
            }

            // Suppress console output from code samples
            var originalOut = Console.Out;
            Console.SetOut(TextWriter.Null);

            try
            {
                var verificationDetailCreateRequest =
                    new GoCardless.Services.VerificationDetailCreateRequest()
                    {
                        Name = "Acme",
                        CompanyNumber = "03768189",
                        AddressLine1 = "12 Drury lane",
                        City = "London",
                        Description = "wine and cheese seller",
                        PostalCode = "B4 7NJ",
                        Directors =
                            new GoCardless.Services.VerificationDetailCreateRequest.VerificationDetailDirectors[]
                            {
                                new GoCardless.Services.VerificationDetailCreateRequest.VerificationDetailDirectors
                                {
                                    GivenName = "Gandalf",
                                    FamilyName = "Grey",
                                    City = "London",
                                    DateOfBirth = "1986-02-19",
                                    Street = "Drury lane",
                                    PostalCode = "B4 7NJ",
                                    CountryCode = "GB",
                                },
                            },
                        Links =
                            new GoCardless.Services.VerificationDetailCreateRequest.VerificationDetailLinks()
                            {
                                Creditor = "CR123",
                            },
                    };

                var verificationDetailResponse = await client.VerificationDetails.CreateAsync(
                    verificationDetailCreateRequest
                );

                var verificationDetail = verificationDetailResponse.VerificationDetail;
            }
            finally
            {
                Console.SetOut(originalOut);
            }
        }
    }
}
