name: build_and_publish
on: push

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      OUT_DIR: "/GoCardless/bin/Release"
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run Tests
      run: dotnet test
    - uses: actions/upload-artifact@v4
      with:
        path: "GoCardless/bin/Release/*.nupkg"

  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
    - build_and_test
    env:
      OUT_DIR: "artifact"
    steps:
    - uses: actions/download-artifact@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Publish the library
      run: dotnet nuget push artifact/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} -n --skip-duplicate
