name: gocardless/gocardless-dotnet/build_and_publish
on:
  push:
    branches:
    - convert-gocardless-gocardless-dotnet-to-actions-20230113-132812
env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      OUT_DIR: "/GoCardless/bin/Release"
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Restore
      run: dotnet restore
    - name: Build
      run: msbuild "GoCardless.sln" /property:Configuration=Release
    - name: Run Tests
      run: dotnet test
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: "/GoCardless/bin/Release/*.nupkg"
  publish:
    if: github.ref == 'refs/heads/convert-gocardless-gocardless-dotnet-to-actions-20230113-132812'
    runs-on: ubuntu-latest
    needs:
    - build_and_test
    env:
      OUT_DIR: "/GoCardless/bin/Release/artifact"
    steps:
    - uses: actions/download-artifact@v3.0.1
      with:
        path: "/GoCardless/bin/Release"
    - name: List
      run: ls -all & ls -all artifact
    