name: gocardless/gocardless-dotnet/build_and_publish
on:
  push:
    branches:
    - master
env:
  NUGET_API_KEY: xxxxzh2m
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      OUT_DIR: "/GoCardless/bin/Release"
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Restore
      run: dotnet restore
    - name: Build
      run: msbuild "GoCardless.sln" /property:Configuration=Release
    - name: Run Tests
      run: dotnet test
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: "/GoCardless/bin/Release/*.nupkg"
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
    - build_and_test
    env:
      OUT_DIR: "/GoCardless/bin/Release"
    steps:
    - uses: actions/download-artifact@v3.0.1
      with:
        path: "/GoCardless/bin/Release"
    - name: Publish the library
      run: dotnet nuget push **\*.nupkg -s https://api.nuget.org/v3/index.json -k %NUGET_API_KEY% -n --skip-duplicate
      shell: cmd.exe
